// Business category / signup purpose master data — transcribed verbatim from
// the taxonomy provided for tenant onboarding. Used by ensureMasterData.ts to
// lazily seed Postgres at runtime (mirrors scripts/data/businessCategories.mjs,
// kept as a standalone-script fallback for manual seeding).

export interface BusinessCategorySeed {
  code: string;
  nameTh: string;
  children: { code: string; nameTh: string }[];
}


export const BUSINESS_CATEGORIES: BusinessCategorySeed[] = [
  {
    code: "food_beverage",
    nameTh: "อาหารและเครื่องดื่ม (Food & Beverage)",
    children: [
      { code: "food_beverage_01", nameTh: "ร้านอาหารตามสั่ง" },
      { code: "food_beverage_02", nameTh: "ร้านอาหารไทย" },
      { code: "food_beverage_03", nameTh: "ร้านอาหารญี่ปุ่น / ซูชิ / ราเมน" },
      { code: "food_beverage_04", nameTh: "ร้านอาหารเกาหลี / ปิ้งย่างเกาหลี" },
      { code: "food_beverage_05", nameTh: "ร้านอาหารจีน / ติ่มซำ" },
      { code: "food_beverage_06", nameTh: "ร้านอาหารอิตาเลียน / พิซซ่า / พาสต้า" },
      { code: "food_beverage_07", nameTh: "ร้านสเต๊ก / เบอร์เกอร์" },
      { code: "food_beverage_08", nameTh: "ร้านอาหารอีสาน / ส้มตำ ไก่ย่าง" },
      { code: "food_beverage_09", nameTh: "ร้านอาหารใต้" },
      { code: "food_beverage_10", nameTh: "ร้านอาหารฮาลาล" },
      { code: "food_beverage_11", nameTh: "ร้านอาหารมังสวิรัติ / เจ / วีแกน" },
      { code: "food_beverage_12", nameTh: "ร้านอาหารทะเล / ซีฟู้ด" },
      { code: "food_beverage_13", nameTh: "ร้านหมูกระทะ / ชาบู / สุกี้ / จิ้มจุ่ม" },
      { code: "food_beverage_14", nameTh: "ร้านก๋วยเตี๋ยว / บะหมี่ / เกาเหลา" },
      { code: "food_beverage_15", nameTh: "ร้านข้าวมันไก่ / ข้าวหมูแดง" },
      { code: "food_beverage_16", nameTh: "ร้านโจ๊ก / ข้าวต้ม" },
      { code: "food_beverage_17", nameTh: "ร้านอาหารเช้า / All-day breakfast" },
      { code: "food_beverage_18", nameTh: "ร้านกาแฟ / คาเฟ่" },
      { code: "food_beverage_19", nameTh: "ร้านชานมไข่มุก / ชาผลไม้" },
      { code: "food_beverage_20", nameTh: "ร้านน้ำผลไม้ / สมูทตี้ / น้ำปั่น" },
      { code: "food_beverage_21", nameTh: "ร้านเบเกอรี่ / เค้ก / ขนมปัง" },
      { code: "food_beverage_22", nameTh: "ร้านโดนัท / ครัวซองต์" },
      { code: "food_beverage_23", nameTh: "ร้านไอศกรีม / เจลาโต้ / บิงซู" },
      { code: "food_beverage_24", nameTh: "ร้านขนมหวานไทย" },
      { code: "food_beverage_25", nameTh: "ร้านขนมเปี๊ยะ / ของฝาก" },
      { code: "food_beverage_26", nameTh: "ร้านสตรีทฟู้ด / รถเข็นขายอาหาร (Food truck)" },
      { code: "food_beverage_27", nameTh: "ร้านอาหารเดลิเวอรีอย่างเดียว (Cloud kitchen / Ghost kitchen)" },
      { code: "food_beverage_28", nameTh: "ธุรกิจรับจัดเลี้ยง / เคเทอริง" },
      { code: "food_beverage_29", nameTh: "ธุรกิจข้าวกล่อง / อาหารคลีนส่งรายเดือน" },
      { code: "food_beverage_30", nameTh: "บาร์ / ผับ / ร้านนั่งดื่ม" },
      { code: "food_beverage_31", nameTh: "ร้านคราฟต์เบียร์ / ไวน์บาร์" },
      { code: "food_beverage_32", nameTh: "ร้านขายวัตถุดิบอาหาร / เครื่องปรุง" },
      { code: "food_beverage_33", nameTh: "โรงงานผลิตอาหาร / OEM อาหาร" },
      { code: "food_beverage_34", nameTh: "ธุรกิจอาหารแช่แข็ง / อาหารพร้อมทาน" },
    ],
  },
  {
    code: "retail_fashion",
    nameTh: "ค้าปลีกและแฟชั่น (Retail & Fashion)",
    children: [
      { code: "retail_fashion_01", nameTh: "ร้านเสื้อผ้าแฟชั่นผู้หญิง" },
      { code: "retail_fashion_02", nameTh: "ร้านเสื้อผ้าผู้ชาย" },
      { code: "retail_fashion_03", nameTh: "ร้านเสื้อผ้าเด็ก / แม่และเด็ก" },
      { code: "retail_fashion_04", nameTh: "ร้านเสื้อผ้าไซซ์ใหญ่" },
      { code: "retail_fashion_05", nameTh: "ร้านเสื้อผ้ามือสอง / วินเทจ" },
      { code: "retail_fashion_06", nameTh: "ร้านชุดชั้นใน / ชุดนอน" },
      { code: "retail_fashion_07", nameTh: "ร้านชุดกีฬา / ชุดว่ายน้ำ" },
      { code: "retail_fashion_08", nameTh: "ร้านชุดยูนิฟอร์ม / ชุดนักเรียน / เสื้อโปโลสกรีน" },
      { code: "retail_fashion_09", nameTh: "ร้านรองเท้า / สนีกเกอร์" },
      { code: "retail_fashion_10", nameTh: "ร้านกระเป๋า / เครื่องหนัง" },
      { code: "retail_fashion_11", nameTh: "ร้านเครื่องประดับ / จิวเวลรี / ร้านทอง" },
      { code: "retail_fashion_12", nameTh: "ร้านนาฬิกา" },
      { code: "retail_fashion_13", nameTh: "ร้านแว่นตา / ร้านตัดแว่น" },
      { code: "retail_fashion_14", nameTh: "ร้านหมวก / เข็มขัด / เครื่องประกอบแฟชั่น" },
      { code: "retail_fashion_15", nameTh: "ร้านผ้า / อุปกรณ์ตัดเย็บ" },
      { code: "retail_fashion_16", nameTh: "ร้านตัดสูท / ตัดชุดสั่งตัด" },
      { code: "retail_fashion_17", nameTh: "ร้านสะดวกซื้อ / มินิมาร์ท" },
      { code: "retail_fashion_18", nameTh: "ซูเปอร์มาร์เก็ต / ร้านขายของชำ (โชห่วย)" },
      { code: "retail_fashion_19", nameTh: "ห้างสรรพสินค้า / ร้านค้าปลีกขนาดใหญ่" },
      { code: "retail_fashion_20", nameTh: "ร้านขายส่ง / ยี่ปั๊ว" },
      { code: "retail_fashion_21", nameTh: "ร้านเครื่องเขียน / อุปกรณ์สำนักงาน" },
      { code: "retail_fashion_22", nameTh: "ร้านหนังสือ / ร้านหนังสือมือสอง" },
      { code: "retail_fashion_23", nameTh: "ร้านของเล่น / โมเดล / ฟิกเกอร์" },
      { code: "retail_fashion_24", nameTh: "ร้านบอร์ดเกม / การ์ดเกม" },
      { code: "retail_fashion_25", nameTh: "ร้านของขวัญ / ของชำร่วย" },
      { code: "retail_fashion_26", nameTh: "ร้านดอกไม้ / รับจัดช่อดอกไม้ / พวงหรีด" },
      { code: "retail_fashion_27", nameTh: "ร้านของแฮนด์เมด / งานคราฟต์" },
      { code: "retail_fashion_28", nameTh: "ร้านสินค้าไลฟ์สไตล์ / ของแต่งบ้านชิ้นเล็ก" },
      { code: "retail_fashion_29", nameTh: "ร้านสินค้ามือสองทั่วไป / รับซื้อของเก่า" },
      { code: "retail_fashion_30", nameTh: "ร้านสินค้านำเข้า / สินค้าญี่ปุ่น-เกาหลี" },
      { code: "retail_fashion_31", nameTh: "ร้านสินค้า 20 บาท / สินค้าราคาเดียว" },
    ],
  },
  {
    code: "beauty_personal_care",
    nameTh: "ความงามและสุขภาพส่วนบุคคล (Beauty & Personal Care)",
    children: [
      { code: "beauty_personal_care_01", nameTh: "ร้านเครื่องสำอาง / มัลติแบรนด์บิวตี้" },
      { code: "beauty_personal_care_02", nameTh: "ร้านน้ำหอม" },
      { code: "beauty_personal_care_03", nameTh: "ร้านสกินแคร์ / ผลิตภัณฑ์บำรุงผิว" },
      { code: "beauty_personal_care_04", nameTh: "แบรนด์เครื่องสำอางของตัวเอง (OEM/ODM)" },
      { code: "beauty_personal_care_05", nameTh: "ร้านทำผม / ซาลอน / บาร์เบอร์" },
      { code: "beauty_personal_care_06", nameTh: "ร้านทำเล็บ / ต่อขนตา" },
      { code: "beauty_personal_care_07", nameTh: "ร้านสักคิ้ว / สักลาย (Tattoo)" },
      { code: "beauty_personal_care_08", nameTh: "คลินิกเสริมความงาม / คลินิกผิวหนัง" },
      { code: "beauty_personal_care_09", nameTh: "คลินิกศัลยกรรม" },
      { code: "beauty_personal_care_10", nameTh: "สปา / นวดแผนไทย / นวดอโรมา" },
      { code: "beauty_personal_care_11", nameTh: "ร้านนวดฝ่าเท้า" },
      { code: "beauty_personal_care_12", nameTh: "ธุรกิจอาหารเสริม / วิตามิน / คอลลาเจน" },
      { code: "beauty_personal_care_13", nameTh: "ร้านวิกผม / ผลิตภัณฑ์ดูแลเส้นผม" },
      { code: "beauty_personal_care_14", nameTh: "ธุรกิจสบู่ / แชมพู / ผลิตภัณฑ์ออร์แกนิก" },
    ],
  },
  {
    code: "healthcare_medical",
    nameTh: "สุขภาพและการแพทย์ (Healthcare & Medical)",
    children: [
      { code: "healthcare_medical_01", nameTh: "โรงพยาบาลเอกชน" },
      { code: "healthcare_medical_02", nameTh: "คลินิกเวชกรรมทั่วไป" },
      { code: "healthcare_medical_03", nameTh: "คลินิกทันตกรรม / จัดฟัน" },
      { code: "healthcare_medical_04", nameTh: "คลินิกกายภาพบำบัด" },
      { code: "healthcare_medical_05", nameTh: "คลินิกแพทย์แผนไทย / แผนจีน / ฝังเข็ม" },
      { code: "healthcare_medical_06", nameTh: "คลินิกจิตเวช / นักจิตวิทยาให้คำปรึกษา" },
      { code: "healthcare_medical_07", nameTh: "คลินิกสัตวแพทย์ (ดูหมวดสัตว์เลี้ยงด้วย)" },
      { code: "healthcare_medical_08", nameTh: "ร้านขายยา / เภสัชกรรม" },
      { code: "healthcare_medical_09", nameTh: "ร้านขายอุปกรณ์การแพทย์ / เครื่องมือแพทย์" },
      { code: "healthcare_medical_10", nameTh: "ศูนย์ตรวจสุขภาพ / แล็บตรวจเลือด" },
      { code: "healthcare_medical_11", nameTh: "ศูนย์ดูแลผู้สูงอายุ / เนอร์สซิ่งโฮม" },
      { code: "healthcare_medical_12", nameTh: "ธุรกิจดูแลผู้ป่วยที่บ้าน / พยาบาลพิเศษ" },
      { code: "healthcare_medical_13", nameTh: "Telemedicine / ปรึกษาแพทย์ออนไลน์" },
      { code: "healthcare_medical_14", nameTh: "ร้านแว่นสายตา / ตรวจวัดสายตา" },
      { code: "healthcare_medical_15", nameTh: "ศูนย์เครื่องช่วยฟัง" },
    ],
  },
  {
    code: "automotive",
    nameTh: "ยานยนต์ (Automotive)",
    children: [
      { code: "automotive_01", nameTh: "โชว์รูมรถยนต์ / ดีลเลอร์รถใหม่" },
      { code: "automotive_02", nameTh: "เต็นท์รถมือสอง" },
      { code: "automotive_03", nameTh: "ร้านขายมอเตอร์ไซค์ / บิ๊กไบค์" },
      { code: "automotive_04", nameTh: "อู่ซ่อมรถยนต์" },
      { code: "automotive_05", nameTh: "อู่ซ่อมมอเตอร์ไซค์" },
      { code: "automotive_06", nameTh: "ศูนย์บริการรถยนต์ / เช็กระยะ" },
      { code: "automotive_07", nameTh: "ร้านซ่อมสีตัวถัง / เคาะพ่นสี" },
      { code: "automotive_08", nameTh: "ร้านยางรถยนต์ / ตั้งศูนย์ถ่วงล้อ" },
      { code: "automotive_09", nameTh: "ร้านแบตเตอรี่รถยนต์" },
      { code: "automotive_10", nameTh: "ร้านล้างรถ / คาร์แคร์ / เคลือบแก้ว เคลือบเซรามิก" },
      { code: "automotive_11", nameTh: "ร้านฟิล์มกรองแสง / ฟิล์มกันรอย (PPF)" },
      { code: "automotive_12", nameTh: "ร้านประดับยนต์ / เครื่องเสียงรถยนต์" },
      { code: "automotive_13", nameTh: "ร้านอะไหล่รถยนต์ / อะไหล่มือสอง (เชียงกง)" },
      { code: "automotive_14", nameTh: "ร้านน้ำมันเครื่อง / เปลี่ยนถ่ายของเหลว" },
      { code: "automotive_15", nameTh: "สถานีชาร์จรถไฟฟ้า (EV Charging)" },
      { code: "automotive_16", nameTh: "ปั๊มน้ำมัน / สถานีบริการ NGV-LPG" },
      { code: "automotive_17", nameTh: "ธุรกิจเช่ารถยนต์ / เช่ามอเตอร์ไซค์" },
      { code: "automotive_18", nameTh: "ธุรกิจรถเช่าพร้อมคนขับ / รถลีมูซีน" },
      { code: "automotive_19", nameTh: "โรงเรียนสอนขับรถ" },
      { code: "automotive_20", nameTh: "ธุรกิจรถยก / รถสไลด์ / ช่วยเหลือฉุกเฉิน" },
      { code: "automotive_21", nameTh: "ตรอ. (ตรวจสภาพรถเอกชน) / รับต่อภาษี-พ.ร.บ." },
      { code: "automotive_22", nameTh: "ร้านจักรยาน / ซ่อมจักรยาน" },
    ],
  },
  {
    code: "home_living",
    nameTh: "บ้าน ที่อยู่อาศัย และงานช่าง (Home & Living)",
    children: [
      { code: "home_living_01", nameTh: "ร้านเฟอร์นิเจอร์" },
      { code: "home_living_02", nameTh: "ร้านที่นอน / เครื่องนอน" },
      { code: "home_living_03", nameTh: "ร้านของแต่งบ้าน / โฮมเดคอร์" },
      { code: "home_living_04", nameTh: "ร้านโคมไฟ / อุปกรณ์แสงสว่าง" },
      { code: "home_living_05", nameTh: "ร้านผ้าม่าน / มู่ลี่ / วอลเปเปอร์" },
      { code: "home_living_06", nameTh: "ร้านเครื่องใช้ไฟฟ้า" },
      { code: "home_living_07", nameTh: "ร้านเครื่องครัว / อุปกรณ์ทำอาหาร" },
      { code: "home_living_08", nameTh: "ร้านวัสดุก่อสร้าง / ฮาร์ดแวร์" },
      { code: "home_living_09", nameTh: "ร้านสี / เคมีภัณฑ์ก่อสร้าง" },
      { code: "home_living_10", nameTh: "ร้านสุขภัณฑ์ / กระเบื้อง" },
      { code: "home_living_11", nameTh: "ร้านประตู-หน้าต่าง / อะลูมิเนียม / กระจก" },
      { code: "home_living_12", nameTh: "ร้านต้นไม้ / อุปกรณ์จัดสวน" },
      { code: "home_living_13", nameTh: "ธุรกิจรับจัดสวน / ดูแลสวน" },
      { code: "home_living_14", nameTh: "ช่างแอร์ / ล้างแอร์ / ติดตั้งแอร์" },
      { code: "home_living_15", nameTh: "ช่างไฟฟ้า / ช่างประปา" },
      { code: "home_living_16", nameTh: "ช่างซ่อมบ้าน / Handyman" },
      { code: "home_living_17", nameTh: "ธุรกิจรับเหมาต่อเติม / รีโนเวท" },
      { code: "home_living_18", nameTh: "ธุรกิจทำความสะอาดบ้าน / แม่บ้านรายชั่วโมง" },
      { code: "home_living_19", nameTh: "ธุรกิจกำจัดปลวก / แมลง" },
      { code: "home_living_20", nameTh: "ธุรกิจติดตั้งโซลาร์เซลล์" },
      { code: "home_living_21", nameTh: "ธุรกิจกล้องวงจรปิด / ระบบรักษาความปลอดภัย" },
      { code: "home_living_22", nameTh: "ธุรกิจซักรีด / ซักอบรีด / ซักผ้าหยอดเหรียญ" },
      { code: "home_living_23", nameTh: "ร้านซ่อมรองเท้า-กระเป๋า / ตีกุญแจ" },
    ],
  },
  {
    code: "finance_insurance",
    nameTh: "การเงิน ประกัน และการลงทุน (Finance & Insurance)",
    children: [
      { code: "finance_insurance_01", nameTh: "ธุรกิจธนาคารพาณิชย์" },
      { code: "finance_insurance_02", nameTh: "ธนาคารดิจิทัล / Virtual Bank / Neobank" },
      { code: "finance_insurance_03", nameTh: "ธุรกิจสินเชื่อส่วนบุคคล" },
      { code: "finance_insurance_04", nameTh: "ธุรกิจสินเชื่อจำนำทะเบียนรถ" },
      { code: "finance_insurance_05", nameTh: "ธุรกิจสินเชื่อบ้าน / รีไฟแนนซ์" },
      { code: "finance_insurance_06", nameTh: "ธุรกิจสินเชื่อ SME / แฟคตอริ่ง" },
      { code: "finance_insurance_07", nameTh: "ธุรกิจเช่าซื้อ / ลีสซิ่ง" },
      { code: "finance_insurance_08", nameTh: "ธุรกิจบัตรเครดิต / บัตรกดเงินสด" },
      { code: "finance_insurance_09", nameTh: "Buy Now Pay Later (ผ่อนก่อนจ่ายทีหลัง)" },
      { code: "finance_insurance_10", nameTh: "โรงรับจำนำ" },
      { code: "finance_insurance_11", nameTh: "ธุรกิจประกันชีวิต" },
      { code: "finance_insurance_12", nameTh: "ธุรกิจประกันวินาศภัย (ประกันรถยนต์, ประกันบ้าน, ประกันอัคคีภัย, ประกันภัยทางทะเล/ขนส่ง)" },
      { code: "finance_insurance_13", nameTh: "ประกันสุขภาพ / ประกันอุบัติเหตุ" },
      { code: "finance_insurance_14", nameTh: "ประกันการเดินทาง" },
      { code: "finance_insurance_15", nameTh: "ประกันสัตว์เลี้ยง" },
      { code: "finance_insurance_16", nameTh: "นายหน้า/โบรกเกอร์ประกัน (Insurance Broker)" },
      { code: "finance_insurance_17", nameTh: "InsurTech / เปรียบเทียบประกันออนไลน์" },
      { code: "finance_insurance_18", nameTh: "บริษัทหลักทรัพย์ / โบรกเกอร์หุ้น" },
      { code: "finance_insurance_19", nameTh: "บริษัทจัดการกองทุน (บลจ.)" },
      { code: "finance_insurance_20", nameTh: "ที่ปรึกษาการเงิน / นักวางแผนการเงิน" },
      { code: "finance_insurance_21", nameTh: "ธุรกิจแลกเปลี่ยนเงินตรา (Money Exchange)" },
      { code: "finance_insurance_22", nameTh: "ธุรกิจโอนเงินระหว่างประเทศ / Remittance" },
      { code: "finance_insurance_23", nameTh: "กระเป๋าเงินดิจิทัล / e-Wallet" },
      { code: "finance_insurance_24", nameTh: "Payment Gateway / ผู้ให้บริการรับชำระเงิน" },
      { code: "finance_insurance_25", nameTh: "ธุรกิจสินทรัพย์ดิจิทัล / Crypto Exchange" },
      { code: "finance_insurance_26", nameTh: "สหกรณ์ออมทรัพย์" },
      { code: "finance_insurance_27", nameTh: "ธุรกิจติดตามทวงหนี้ / บริหารหนี้" },
    ],
  },
  {
    code: "education",
    nameTh: "การศึกษา (Education)",
    children: [
      { code: "education_01", nameTh: "โรงเรียนเอกชน / โรงเรียนนานาชาติ" },
      { code: "education_02", nameTh: "โรงเรียนอนุบาล / เนอสเซอรี่ / เดย์แคร์" },
      { code: "education_03", nameTh: "มหาวิทยาลัย / วิทยาลัยเอกชน" },
      { code: "education_04", nameTh: "โรงเรียนกวดวิชา / ติวเตอร์" },
      { code: "education_05", nameTh: "สถาบันสอนภาษา (อังกฤษ, จีน, ญี่ปุ่น, เกาหลี)" },
      { code: "education_06", nameTh: "โรงเรียนสอนดนตรี / ร้องเพลง" },
      { code: "education_07", nameTh: "โรงเรียนสอนศิลปะ / วาดรูป" },
      { code: "education_08", nameTh: "โรงเรียนสอนเต้น / บัลเลต์" },
      { code: "education_09", nameTh: "โรงเรียนสอนทำอาหาร / เบเกอรี่" },
      { code: "education_10", nameTh: "โรงเรียนสอนว่ายน้ำ" },
      { code: "education_11", nameTh: "สถาบันสอนเขียนโปรแกรม / Coding" },
      { code: "education_12", nameTh: "คอร์สออนไลน์ / e-Learning platform" },
      { code: "education_13", nameTh: "ติวสอบ / เตรียมสอบราชการ-IELTS-TOEIC" },
      { code: "education_14", nameTh: "สถาบันพัฒนาทักษะอาชีพ / อบรมองค์กร" },
      { code: "education_15", nameTh: "โรงเรียนสอนขับรถ (ดูหมวดยานยนต์ด้วย)" },
    ],
  },
  {
    code: "hospitality_travel_leisure",
    nameTh: "ท่องเที่ยว โรงแรม และสันทนาการ (Hospitality, Travel & Leisure)",
    children: [
      { code: "hospitality_travel_leisure_01", nameTh: "โรงแรม / รีสอร์ต" },
      { code: "hospitality_travel_leisure_02", nameTh: "โฮสเทล / เกสต์เฮาส์" },
      { code: "hospitality_travel_leisure_03", nameTh: "โฮมสเตย์ / ที่พักเชิงเกษตร" },
      { code: "hospitality_travel_leisure_04", nameTh: "เซอร์วิสอพาร์ตเมนต์" },
      { code: "hospitality_travel_leisure_05", nameTh: "บริษัททัวร์ / ตัวแทนท่องเที่ยว (Travel Agency)" },
      { code: "hospitality_travel_leisure_06", nameTh: "ทัวร์นำเที่ยวท้องถิ่น / ไกด์ / One-day trip" },
      { code: "hospitality_travel_leisure_07", nameTh: "แพลตฟอร์มจองที่พัก / จองตั๋ว (OTA)" },
      { code: "hospitality_travel_leisure_08", nameTh: "สายการบิน" },
      { code: "hospitality_travel_leisure_09", nameTh: "ธุรกิจเรือนำเที่ยว / เรือเช่าเหมาลำ / ยอทช์" },
      { code: "hospitality_travel_leisure_10", nameTh: "ธุรกิจรถตู้-รถบัสเช่าเหมา" },
      { code: "hospitality_travel_leisure_11", nameTh: "แคมป์ปิ้ง / ลานกางเต็นท์ / กลามปิ้ง" },
      { code: "hospitality_travel_leisure_12", nameTh: "สวนสนุก / สวนน้ำ" },
      { code: "hospitality_travel_leisure_13", nameTh: "สวนสัตว์ / อควาเรียม" },
      { code: "hospitality_travel_leisure_14", nameTh: "พิพิธภัณฑ์ / แกลเลอรีศิลปะ" },
      { code: "hospitality_travel_leisure_15", nameTh: "คาเฟ่แมว / คาเฟ่สัตว์" },
      { code: "hospitality_travel_leisure_16", nameTh: "คาราโอเกะ" },
      { code: "hospitality_travel_leisure_17", nameTh: "โบว์ลิ่ง / สนุกเกอร์ / พูล" },
      { code: "hospitality_travel_leisure_18", nameTh: "ร้านเกม / อินเทอร์เน็ตคาเฟ่ / E-sport arena" },
      { code: "hospitality_travel_leisure_19", nameTh: "ห้องหนีตาย (Escape room) / บอร์ดเกมคาเฟ่" },
      { code: "hospitality_travel_leisure_20", nameTh: "สวนสาธารณะเอกชน / ฟาร์มท่องเที่ยว" },
      { code: "hospitality_travel_leisure_21", nameTh: "ธุรกิจดำน้ำ / กีฬาทางน้ำ" },
      { code: "hospitality_travel_leisure_22", nameTh: "สนามยิงปืน / ยิงธนู / เพนต์บอล" },
      { code: "hospitality_travel_leisure_23", nameTh: "สนามกอล์ฟ / ไดรฟ์กอล์ฟ" },
    ],
  },
  {
    code: "sports_fitness",
    nameTh: "กีฬาและฟิตเนส (Sports & Fitness)",
    children: [
      { code: "sports_fitness_01", nameTh: "ฟิตเนส / ยิม" },
      { code: "sports_fitness_02", nameTh: "สตูดิโอโยคะ / พิลาทิส" },
      { code: "sports_fitness_03", nameTh: "ค่ายมวย / ยิมมวยไทย" },
      { code: "sports_fitness_04", nameTh: "คลาสเต้น / Zumba / แอโรบิก" },
      { code: "sports_fitness_05", nameTh: "เทรนเนอร์ส่วนตัว (Personal Trainer)" },
      { code: "sports_fitness_06", nameTh: "สนามฟุตบอลหญ้าเทียมให้เช่า" },
      { code: "sports_fitness_07", nameTh: "สนามแบดมินตัน / เทนนิสให้เช่า" },
      { code: "sports_fitness_08", nameTh: "สระว่ายน้ำ / สอนว่ายน้ำ" },
      { code: "sports_fitness_09", nameTh: "สนามปีนผา (Climbing gym)" },
      { code: "sports_fitness_10", nameTh: "ร้านขายอุปกรณ์กีฬา" },
      { code: "sports_fitness_11", nameTh: "ร้านจักรยาน / อุปกรณ์ปั่นจักรยาน" },
      { code: "sports_fitness_12", nameTh: "ร้านอุปกรณ์ตกปลา / แคมป์ปิ้ง" },
      { code: "sports_fitness_13", nameTh: "ธุรกิจจัดแข่งวิ่ง / มาราธอน / ไตรกีฬา" },
      { code: "sports_fitness_14", nameTh: "สโมสรกีฬา / อคาเดมีฟุตบอล" },
    ],
  },
  {
    code: "pets",
    nameTh: "สัตว์เลี้ยง (Pets)",
    children: [
      { code: "pets_01", nameTh: "ร้านขายสัตว์เลี้ยง / ฟาร์มเพาะพันธุ์" },
      { code: "pets_02", nameTh: "ร้านอาหารสัตว์ / อุปกรณ์สัตว์เลี้ยง" },
      { code: "pets_03", nameTh: "ร้านอาบน้ำ-ตัดขนสัตว์ (Grooming)" },
      { code: "pets_04", nameTh: "โรงแรมสัตว์เลี้ยง / รับฝากเลี้ยง" },
      { code: "pets_05", nameTh: "คลินิก/โรงพยาบาลสัตว์" },
      { code: "pets_06", nameTh: "ธุรกิจรับพาสุนัขเดินเล่น / พี่เลี้ยงสัตว์" },
      { code: "pets_07", nameTh: "คาเฟ่สัตว์เลี้ยง" },
      { code: "pets_08", nameTh: "ธุรกิจฌาปนกิจสัตว์เลี้ยง" },
      { code: "pets_09", nameTh: "ประกันสัตว์เลี้ยง (ดูหมวดการเงินด้วย)" },
    ],
  },
  {
    code: "technology_digital",
    nameTh: "เทคโนโลยีและดิจิทัล (Technology & Digital)",
    children: [
      { code: "technology_digital_01", nameTh: "บริษัทพัฒนาซอฟต์แวร์ / Software House" },
      { code: "technology_digital_02", nameTh: "SaaS (ซอฟต์แวร์แบบสมัครสมาชิก เช่น บัญชี, CRM, HR, POS)" },
      { code: "technology_digital_03", nameTh: "บริษัท AI / Machine Learning / แชทบอท" },
      { code: "technology_digital_04", nameTh: "บริษัทพัฒนาแอปมือถือ" },
      { code: "technology_digital_05", nameTh: "บริษัทพัฒนาเว็บไซต์ / เว็บเอเจนซี" },
      { code: "technology_digital_06", nameTh: "ธุรกิจ Cloud / Hosting / Data Center" },
      { code: "technology_digital_07", nameTh: "ธุรกิจ Cybersecurity" },
      { code: "technology_digital_08", nameTh: "ธุรกิจ IoT / Smart Home" },
      { code: "technology_digital_09", nameTh: "ธุรกิจเกม / เกมสตูดิโอ" },
      { code: "technology_digital_10", nameTh: "ธุรกิจบล็อกเชน / Web3 / NFT" },
      { code: "technology_digital_11", nameTh: "ร้านขายคอมพิวเตอร์ / โน้ตบุ๊ก / อุปกรณ์ไอที" },
      { code: "technology_digital_12", nameTh: "ร้านมือถือ / อุปกรณ์เสริม" },
      { code: "technology_digital_13", nameTh: "ร้านซ่อมมือถือ / ซ่อมคอมพิวเตอร์" },
      { code: "technology_digital_14", nameTh: "ร้านกล้อง / อุปกรณ์ถ่ายภาพ" },
      { code: "technology_digital_15", nameTh: "ธุรกิจโดรน / ถ่ายภาพมุมสูง" },
      { code: "technology_digital_16", nameTh: "ธุรกิจติดตั้งระบบเน็ตเวิร์ก / IT Support องค์กร" },
      { code: "technology_digital_17", nameTh: "ผู้ให้บริการอินเทอร์เน็ต / โทรคมนาคม" },
    ],
  },
  {
    code: "media_entertainment_creator",
    nameTh: "สื่อ บันเทิง และครีเอเตอร์ (Media, Entertainment & Creator)",
    children: [
      { code: "media_entertainment_creator_01", nameTh: "สตรีมมิงหนัง / ซีรีส์ / เพลง" },
      { code: "media_entertainment_creator_02", nameTh: "ค่ายเพลง / ศิลปิน" },
      { code: "media_entertainment_creator_03", nameTh: "สำนักข่าว / นิตยสาร / สื่อออนไลน์" },
      { code: "media_entertainment_creator_04", nameTh: "สำนักพิมพ์ / e-Book" },
      { code: "media_entertainment_creator_05", nameTh: "โปรดักชันเฮาส์ / ถ่ายทำวิดีโอ" },
      { code: "media_entertainment_creator_06", nameTh: "สตูดิโอถ่ายภาพ / ช่างภาพรับจ้าง" },
      { code: "media_entertainment_creator_07", nameTh: "ธุรกิจจัดคอนเสิร์ต / เทศกาลดนตรี" },
      { code: "media_entertainment_creator_08", nameTh: "แพลตฟอร์มขายบัตร / Ticketing" },
      { code: "media_entertainment_creator_09", nameTh: "โรงภาพยนตร์ / โรงละคร" },
      { code: "media_entertainment_creator_10", nameTh: "ยูทูบเบอร์ / สตรีมเมอร์ / อินฟลูเอนเซอร์" },
      { code: "media_entertainment_creator_11", nameTh: "พอดแคสต์" },
      { code: "media_entertainment_creator_12", nameTh: "ครีเอเตอร์คอร์สออนไลน์ / Membership / Newsletter" },
      { code: "media_entertainment_creator_13", nameTh: "เอเจนซีดูแลอินฟลูเอนเซอร์ (MCN)" },
      { code: "media_entertainment_creator_14", nameTh: "ธุรกิจเช่าชุด / เช่าอุปกรณ์ถ่ายทำ" },
      { code: "media_entertainment_creator_15", nameTh: "สตูดิโอให้เช่าถ่ายงาน" },
    ],
  },
  {
    code: "professional_business_services",
    nameTh: "บริการมืออาชีพและธุรกิจ B2B (Professional & Business Services)",
    children: [
      { code: "professional_business_services_01", nameTh: "สำนักงานบัญชี / ตรวจสอบบัญชี" },
      { code: "professional_business_services_02", nameTh: "สำนักงานกฎหมาย / ทนายความ / โนตารี" },
      { code: "professional_business_services_03", nameTh: "ที่ปรึกษาภาษี / จดทะเบียนบริษัท" },
      { code: "professional_business_services_04", nameTh: "ที่ปรึกษาธุรกิจ / Management Consulting" },
      { code: "professional_business_services_05", nameTh: "เอเจนซีการตลาด / โฆษณา / Digital Marketing" },
      { code: "professional_business_services_06", nameTh: "เอเจนซีรับยิงแอด / SEO / Social Media" },
      { code: "professional_business_services_07", nameTh: "บริษัทรับออกแบบกราฟิก / แบรนดิ้ง" },
      { code: "professional_business_services_08", nameTh: "บริษัทสถาปนิก / ออกแบบตกแต่งภายใน" },
      { code: "professional_business_services_09", nameTh: "บริษัทจัดหางาน / Recruitment / Outsource" },
      { code: "professional_business_services_10", nameTh: "บริษัทรับจ้างทำเงินเดือน (Payroll)" },
      { code: "professional_business_services_11", nameTh: "ธุรกิจแปลภาษา / ล่าม" },
      { code: "professional_business_services_12", nameTh: "ธุรกิจรับรองเอกสาร / วีซ่า / Work permit" },
      { code: "professional_business_services_13", nameTh: "โคเวิร์กกิ้งสเปซ / ออฟฟิศให้เช่า" },
      { code: "professional_business_services_14", nameTh: "Virtual Office / รับจดทะเบียนที่อยู่" },
      { code: "professional_business_services_15", nameTh: "บริษัทวิจัยตลาด / Data Analytics" },
      { code: "professional_business_services_16", nameTh: "ธุรกิจถ่ายเอกสาร / งานพิมพ์ / โรงพิมพ์" },
      { code: "professional_business_services_17", nameTh: "ร้านป้าย / ป้ายไฟ / สติกเกอร์ / อิงค์เจ็ท" },
      { code: "professional_business_services_18", nameTh: "ธุรกิจรักษาความปลอดภัย (รปภ.)" },
      { code: "professional_business_services_19", nameTh: "ธุรกิจทำความสะอาดสำนักงาน / อาคาร" },
      { code: "professional_business_services_20", nameTh: "นักสืบเอกชน" },
    ],
  },
  {
    code: "agriculture",
    nameTh: "เกษตรและอาหารต้นน้ำ (Agriculture)",
    children: [
      { code: "agriculture_01", nameTh: "ฟาร์มผัก / ผักไฮโดรโปนิกส์ / ผักออร์แกนิก" },
      { code: "agriculture_02", nameTh: "สวนผลไม้ / ส่งออกผลไม้" },
      { code: "agriculture_03", nameTh: "ฟาร์มเห็ด" },
      { code: "agriculture_04", nameTh: "นาข้าว / โรงสีข้าว" },
      { code: "agriculture_05", nameTh: "ฟาร์มปศุสัตว์ (หมู, ไก่, วัว)" },
      { code: "agriculture_06", nameTh: "ฟาร์มไข่ไก่" },
      { code: "agriculture_07", nameTh: "ฟาร์มกุ้ง / บ่อปลา / ประมง" },
      { code: "agriculture_08", nameTh: "ธุรกิจเมล็ดพันธุ์ / ต้นกล้า" },
      { code: "agriculture_09", nameTh: "ร้านขายปุ๋ย / ยา / อุปกรณ์การเกษตร" },
      { code: "agriculture_10", nameTh: "ธุรกิจเครื่องจักรกลการเกษตร / โดรนพ่นยา" },
      { code: "agriculture_11", nameTh: "ธุรกิจแปรรูปสินค้าเกษตร" },
      { code: "agriculture_12", nameTh: "ตลาดกลางสินค้าเกษตร / รับซื้อผลผลิต" },
      { code: "agriculture_13", nameTh: "ฟาร์มกัญชง-กัญชา (ตามใบอนุญาต)" },
      { code: "agriculture_14", nameTh: "ธุรกิจปลูกไม้ดอกไม้ประดับ / กล้วยไม้ส่งออก" },
    ],
  },
  {
    code: "real_estate_construction",
    nameTh: "อสังหาริมทรัพย์และก่อสร้าง (Real Estate & Construction)",
    children: [
      { code: "real_estate_construction_01", nameTh: "บริษัทพัฒนาอสังหาริมทรัพย์ (บ้านจัดสรร, คอนโด)" },
      { code: "real_estate_construction_02", nameTh: "นายหน้าอสังหาริมทรัพย์ / เอเจนต์ซื้อ-ขาย-เช่า" },
      { code: "real_estate_construction_03", nameTh: "ธุรกิจบริหารนิติบุคคลอาคารชุด/หมู่บ้าน" },
      { code: "real_estate_construction_04", nameTh: "อพาร์ตเมนต์ / หอพักให้เช่า" },
      { code: "real_estate_construction_05", nameTh: "ธุรกิจปล่อยเช่ารายวัน / Airbnb host" },
      { code: "real_estate_construction_06", nameTh: "ธุรกิจโกดัง / คลังสินค้าให้เช่า" },
      { code: "real_estate_construction_07", nameTh: "ธุรกิจห้องเก็บของให้เช่า (Self-storage)" },
      { code: "real_estate_construction_08", nameTh: "บริษัทรับเหมาก่อสร้าง" },
      { code: "real_estate_construction_09", nameTh: "บริษัทรับสร้างบ้าน" },
      { code: "real_estate_construction_10", nameTh: "ธุรกิจให้เช่าเครื่องจักรก่อสร้าง / นั่งร้าน" },
      { code: "real_estate_construction_11", nameTh: "ธุรกิจประเมินราคาทรัพย์สิน" },
      { code: "real_estate_construction_12", nameTh: "ธุรกิจตรวจรับบ้าน-คอนโด (Inspector)" },
    ],
  },
  {
    code: "transport_logistics",
    nameTh: "ขนส่งและโลจิสติกส์ (Transport & Logistics)",
    children: [
      { code: "transport_logistics_01", nameTh: "บริษัทขนส่งพัสดุ / Express delivery" },
      { code: "transport_logistics_02", nameTh: "แฟรนไชส์จุดรับส่งพัสดุ / Drop-off point" },
      { code: "transport_logistics_03", nameTh: "ธุรกิจขนส่งสินค้า / รถบรรทุก / รถหัวลาก" },
      { code: "transport_logistics_04", nameTh: "ธุรกิจขนส่งควบคุมอุณหภูมิ (Cold chain)" },
      { code: "transport_logistics_05", nameTh: "Freight Forwarder / ชิปปิ้ง / นำเข้า-ส่งออก" },
      { code: "transport_logistics_06", nameTh: "ตัวแทนออกของ / พิธีการศุลกากร" },
      { code: "transport_logistics_07", nameTh: "ธุรกิจคลังสินค้า / Fulfillment" },
      { code: "transport_logistics_08", nameTh: "บริการแมสเซนเจอร์ / ส่งเอกสารด่วน" },
      { code: "transport_logistics_09", nameTh: "แอปเรียกรถ / Ride-hailing" },
      { code: "transport_logistics_10", nameTh: "แท็กซี่ / วินมอเตอร์ไซค์" },
      { code: "transport_logistics_11", nameTh: "รถทัวร์ / รถโดยสารประจำทาง" },
      { code: "transport_logistics_12", nameTh: "ธุรกิจขนย้ายบ้าน / ขนย้ายสำนักงาน" },
      { code: "transport_logistics_13", nameTh: "ธุรกิจพรีออเดอร์ / รับหิ้วสินค้าต่างประเทศ" },
    ],
  },
  {
    code: "events_ceremonies",
    nameTh: "งานอีเวนต์และพิธีการ (Events & Ceremonies)",
    children: [
      { code: "events_ceremonies_01", nameTh: "ออแกไนเซอร์รับจัดงานอีเวนต์" },
      { code: "events_ceremonies_02", nameTh: "ธุรกิจรับจัดงานแต่งงาน (Wedding planner)" },
      { code: "events_ceremonies_03", nameTh: "สตูดิโอถ่ายพรีเวดดิ้ง" },
      { code: "events_ceremonies_04", nameTh: "ธุรกิจเช่าชุดแต่งงาน / ชุดราตรี" },
      { code: "events_ceremonies_05", nameTh: "ร้านเช่าเต็นท์ / โต๊ะ เก้าอี้ / เครื่องเสียง / ไฟ" },
      { code: "events_ceremonies_06", nameTh: "ธุรกิจรับจัดดอกไม้งานพิธี / แบ็คดรอป / บอลลูน" },
      { code: "events_ceremonies_07", nameTh: "MC / พิธีกร / วงดนตรีงานแต่ง" },
      { code: "events_ceremonies_08", nameTh: "ธุรกิจจัดงานศพ / สุริยาหีบศพ / ฌาปนกิจ" },
      { code: "events_ceremonies_09", nameTh: "ธุรกิจรับจัดงานบวช / งานบุญ" },
      { code: "events_ceremonies_10", nameTh: "ธุรกิจจัดสัมมนา / นิทรรศการ / บูธแสดงสินค้า" },
      { code: "events_ceremonies_11", nameTh: "ธุรกิจเช่าตู้ถ่ายรูป (Photo booth)" },
    ],
  },
  {
    code: "nonprofit_public_sector",
    nameTh: "องค์กรไม่แสวงกำไรและภาครัฐ (Non-profit & Public Sector)",
    children: [
      { code: "nonprofit_public_sector_01", nameTh: "มูลนิธิ / องค์กรการกุศล" },
      { code: "nonprofit_public_sector_02", nameTh: "NGO / องค์กรพัฒนาเอกชน" },
      { code: "nonprofit_public_sector_03", nameTh: "วัด / โบสถ์ / มัสยิด / ศาสนสถาน (รับบริจาคออนไลน์)" },
      { code: "nonprofit_public_sector_04", nameTh: "สมาคม / ชมรม / สหภาพ" },
      { code: "nonprofit_public_sector_05", nameTh: "สถานสงเคราะห์ / บ้านพักพิง" },
      { code: "nonprofit_public_sector_06", nameTh: "หน่วยงานราชการ / รัฐวิสาหกิจ" },
      { code: "nonprofit_public_sector_07", nameTh: "องค์กรปกครองส่วนท้องถิ่น (อบต. / เทศบาล)" },
      { code: "nonprofit_public_sector_08", nameTh: "สถาบันการศึกษาของรัฐ" },
      { code: "nonprofit_public_sector_09", nameTh: "แพลตฟอร์มระดมทุน / Crowdfunding / Donation" },
    ],
  },
  {
    code: "manufacturing_industrial",
    nameTh: "อุตสาหกรรมและการผลิต (Manufacturing & Industrial)",
    children: [
      { code: "manufacturing_industrial_01", nameTh: "โรงงานผลิตสินค้าอุปโภคบริโภค (FMCG)" },
      { code: "manufacturing_industrial_02", nameTh: "โรงงานรับผลิต OEM/ODM (เครื่องสำอาง, อาหารเสริม, เสื้อผ้า)" },
      { code: "manufacturing_industrial_03", nameTh: "โรงงานพลาสติก / บรรจุภัณฑ์ / กล่องกระดาษ" },
      { code: "manufacturing_industrial_04", nameTh: "โรงงานสิ่งทอ / โรงงานตัดเย็บ" },
      { code: "manufacturing_industrial_05", nameTh: "โรงกลึง / งานโลหะ / เชื่อมเหล็ก" },
      { code: "manufacturing_industrial_06", nameTh: "โรงงานเฟอร์นิเจอร์" },
      { code: "manufacturing_industrial_07", nameTh: "ธุรกิจเคมีภัณฑ์อุตสาหกรรม" },
      { code: "manufacturing_industrial_08", nameTh: "ธุรกิจขายเครื่องจักร / อะไหล่อุตสาหกรรม" },
      { code: "manufacturing_industrial_09", nameTh: "ธุรกิจรีไซเคิล / รับซื้อเศษเหล็ก-กระดาษ-พลาสติก" },
      { code: "manufacturing_industrial_10", nameTh: "ธุรกิจพลังงาน / โซลาร์ฟาร์ม" },
      { code: "manufacturing_industrial_11", nameTh: "ธุรกิจบำบัดน้ำเสีย / สิ่งแวดล้อม" },
    ],
  },
  {
    code: "online_platforms",
    nameTh: "ออนไลน์และแพลตฟอร์ม (Online Business & Platforms)",
    children: [
      { code: "online_platforms_01", nameTh: "ร้านค้าออนไลน์ทั่วไป (ขายผ่านโซเชียล / Marketplace)" },
      { code: "online_platforms_02", nameTh: "แบรนด์ D2C (ขายตรงถึงผู้บริโภคผ่านเว็บตัวเอง)" },
      { code: "online_platforms_03", nameTh: "ธุรกิจดรอปชิป (Dropshipping)" },
      { code: "online_platforms_04", nameTh: "ธุรกิจตัวแทนจำหน่าย / แม่ทีมขายของออนไลน์" },
      { code: "online_platforms_05", nameTh: "ธุรกิจไลฟ์ขายของ (Live commerce)" },
      { code: "online_platforms_06", nameTh: "แพลตฟอร์มมาร์เก็ตเพลส (ตลาดกลางซื้อ-ขาย)" },
      { code: "online_platforms_07", nameTh: "แพลตฟอร์มสินค้ามือสอง" },
      { code: "online_platforms_08", nameTh: "แพลตฟอร์มจองคิวบริการ (ร้านเสริมสวย, ช่าง, คลินิก)" },
      { code: "online_platforms_09", nameTh: "แพลตฟอร์มฟรีแลนซ์ / จ้างงาน" },
      { code: "online_platforms_10", nameTh: "แพลตฟอร์มเดลิเวอรีอาหาร / ของสด" },
      { code: "online_platforms_11", nameTh: "แพลตฟอร์มอสังหา / รถมือสอง (Classified)" },
      { code: "online_platforms_12", nameTh: "ธุรกิจ Affiliate / รีวิวสินค้า" },
      { code: "online_platforms_13", nameTh: "ธุรกิจขายสินค้าดิจิทัล (Template, Preset, Sticker, Font)" },
      { code: "online_platforms_14", nameTh: "ธุรกิจ Subscription box (กล่องสุ่มรายเดือน)" },
    ],
  },
];

export const SIGNUP_PURPOSES: { code: string; nameTh: string }[] = [
  { code: "trade_commerce", nameTh: "เพื่อทำธุรกิจค้าขาย" },
  { code: "academic", nameTh: "เพื่อทำงานด้านวิชาการ" },
  { code: "hotel_dormitory", nameTh: "เพื่อธุรกิจโรงแรม/หอพัก" },
  { code: "internal_org", nameTh: "เพื่อใช้งานระบบภายในองค์กร" },
  { code: "pr_information", nameTh: "เพื่อการประชาสัมพันธ์และให้ข้อมูล" },
  { code: "registration_signup", nameTh: "เพื่อการลงทะเบียนสมัคร" },
];
