import type { PublicPricingSnapshot } from "@/lib/pricing/buildPublicPricing";

/**
 * Static fallback — ใช้เมื่อ API/hook ล้มเหลว (backward compatible กับ UI เดิม)
 */
export const STATIC_PRICING_FALLBACK: PublicPricingSnapshot = {
  updatedAt: "static-fallback",
  basePlans: [
    {
      id: "starter",
      tier: "Starter",
      label: "Starter",
      checkoutPlanId: "starter",
      retailPrice: 990,
      retailInclVat: 990,
      messageQuota: 2000,
      isPopular: false,
      features: [
        "บอทตอบลูกค้า 24/7",
        "Knowledge Base ไม่จำกัด",
        "Widget embed พร้อมใช้",
        "Analytics พื้นฐาน",
        "Email support",
      ],
    },
    {
      id: "pro",
      tier: "Pro",
      label: "Pro",
      checkoutPlanId: "pro",
      retailPrice: 1990,
      retailInclVat: 1990,
      messageQuota: 5000,
      isPopular: true,
      features: [
        "ทุกอย่างใน Starter",
        "Buying Signal Detection",
        "LINE Notify แจ้งเตือน",
        "Analytics ครบ",
        "Priority support",
        "Domain Whitelist",
      ],
    },
    {
      id: "master",
      tier: "Master",
      label: "Master",
      checkoutPlanId: "master",
      retailPrice: 14990,
      retailInclVat: 14990,
      messageQuota: 20000,
      isPopular: false,
      features: [
        "ทุกอย่างใน Pro",
        "Visitor Personality Learning",
        "Custom Engagement Rules",
        "ส่งออกข้อมูล Analytics",
        "Dedicated support",
        "SLA 99.9%",
      ],
    },
  ],
  quotaAddons: [
    {
      id: "quota_1k",
      checkoutAddonId: "quota_1k",
      label: "+1,000 ข้อความ/เดือน",
      extraMessages: 1000,
      retailPrice: 249,
      tag: null,
    },
    {
      id: "quota_5k",
      checkoutAddonId: "quota_5k",
      label: "+5,000 ข้อความ/เดือน",
      extraMessages: 5000,
      retailPrice: 690,
      tag: "คุ้มค่า",
    },
    {
      id: "quota_20k",
      checkoutAddonId: "quota_20k",
      label: "+20,000 ข้อความ/เดือน",
      extraMessages: 20000,
      retailPrice: 2290,
      tag: null,
    },
  ],
  retentionAddons: [
    {
      id: "ret_7d",
      periodLabel: "7 วัน",
      retentionDays: 7,
      retailPrice: 0,
      displayPrice: "ฟรี",
      tag: "มาตรฐาน",
    },
    {
      id: "ret_30d",
      periodLabel: "30 วัน",
      retentionDays: 30,
      retailPrice: 349,
      displayPrice: "349",
      tag: null,
    },
    {
      id: "ret_90d",
      periodLabel: "90 วัน",
      retentionDays: 90,
      retailPrice: 790,
      displayPrice: "790",
      tag: "ยอดนิยม",
    },
    {
      id: "ret_life",
      periodLabel: "ตลอดไป",
      retentionDays: -1,
      retailPrice: -1,
      displayPrice: "Custom",
      tag: "สำหรับองค์กร",
    },
  ],
  partnerPlans: [
    {
      id: "starter",
      name: "🌱 Starter",
      msgs: "2,000",
      retail: "฿990",
      wholesale: "฿545",
      profit: "฿445",
      pct: "45%",
      popular: false,
      retailNum: 990,
      profitNum: 445,
    },
    {
      id: "pro",
      name: "⭐ Pro",
      msgs: "5,000",
      retail: "฿1,990",
      wholesale: "฿1,095",
      profit: "฿895",
      pct: "45%",
      popular: true,
      retailNum: 1990,
      profitNum: 895,
    },
    {
      id: "master",
      name: "👑 Master",
      msgs: "20,000",
      retail: "฿14,990",
      wholesale: "฿8,245",
      profit: "฿6,745",
      pct: "45%",
      popular: false,
      retailNum: 14990,
      profitNum: 6745,
    },
  ],
};
